name: aviz_project
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  pinput: ^3.0.1
  step_progress_indicator: ^1.0.2
  dotted_border: ^2.1.0
  fdottedline_nullsafety: ^2.0.1
  dotted_line: ^3.2.2
  image_picker: ^1.0.5
  intl: ^0.19.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: SN
      fonts:
        - asset: assets/fonts/Shabnam.ttf
 
